version: '3'
services:
  app-gateway-test: 
    image: node
    user: node:node
    working_dir: /app
    container_name: app-gateway-test
    depends_on:
      - rabbitmq
    ports: 
      - '5010:3000'
    networks:
      - default-test
    volumes:
      - ./:/app
    command: 'npm run start:dev'

  app-courses-test:
      image: node
      user: node:node
      working_dir: /app
      container_name: app-courses-test
      environment:
        DATABASE_URL: postgresql://postgres:secret@postgres-db-courses-test:5432/db_courses_test?schema=public
      depends_on:
        - postgres-db-courses-test
        - rabbitmq
      ports: 
        - '5011:3000'
      networks:
        - default-test
      volumes:
        - ../app-courses/:/app
      command: 'npm run start:dev'

  postgres-db-courses-test:
    image: postgres
    container_name: postgres-db-courses-test
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRESS_DB: db_courses_test
    ports:
      - '5433:5432'
    volumes:
      - db_courses:/var/lib/postgresql/data
    networks:
      - default-test

  app-certifications-test: 
    image: node
    user: node:node
    working_dir: /app
    container_name: app-certifications-test
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres-db-certifications-test:5432/db_certifications_test?schema=public
    depends_on:
      - postgres-db-certifications-test
      - rabbitmq
    ports: 
      - '5012:3000'
    networks:
      - default-test
    volumes:
      - ../app-certifications/:/app
    command: 'npm run start:dev'

  postgres-db-certifications-test:
    image: postgres
    container_name: postgres-db-certifications-test
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRESS_DB: db_certifications_test
    ports:
      - '5435:5432'
    volumes:
      - db_certifications:/var/lib/postgresql/data
    networks:
      - default-test

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq-test
    hostname: rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default-test

volumes:
  db_courses:
    driver: local
  db_certifications:
    driver: local
networks:
  default-test:
    driver: bridge